---
name: Lint

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  fix-lint-issues:
    permissions:
      contents: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.CLUSTER_API_REPO_TOKEN }}


      - name: Super-Linter
        uses: super-linter/super-linter@v8.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push linting fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          commit_message: "chore: fix linting issues"
          commit_user_name: super-linter
          commit_user_email: super-linter@super-linter.dev

env:
  LINTER_RULES_PATH: /
  VALIDATE_TRIVY: false
  VALIDATE_JSCPD: false
  VALIDATE_PYTHON: true
  VALIDATE_CHECKOV: false
  VALIDATE_MARKDOWN: false
  VALIDATE_BIOME_LINT: false
  VALIDATE_BIOME_FORMAT: false
  VALIDATE_ALL_CODEBASE: false
  VALIDATE_PYTHON_ISORT: false
  VALIDATE_PYTHON_PYLINT: false
  VALIDATE_YAML_PRETTIER: false
  VALIDATE_PYTHON_FLAKE8: false
  VALIDATE_MARKDOWN_PRETTIER: false
  VALIDATE_PYTHON_RUFF_FORMAT: false
  VALIDATE_DOCKERFILE_HADOLINT: false
  VALIDATE_GITHUB_ACTIONS_ZIZMOR: false
  FIX_PYTHON_RUFF: true
  FIX_PYTHON_BLACK: true
